spring:
  application:
    name: grpc-manri-hyang

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ManLiHyang
    username: root
    password: apmsetup