// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.example.demo.grpc.board;

public interface BoardDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.board.BoardDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 user_id = 2;</code>
   */
  long getUserId();

  /**
   * <code>string title = 3;</code>
   */
  String getTitle();
  /**
   * <code>string title = 3;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string image_url = 4;</code>
   */
  String getImageUrl();
  /**
   * <code>string image_url = 4;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>int32 likes = 5;</code>
   */
  int getLikes();

  /**
   * <code>int32 group_id = 6;</code>
   */
  int getGroupId();

  /**
   * <code>int32 group_seq = 7;</code>
   */
  int getGroupSeq();

  /**
   * <code>int32 group_depth = 8;</code>
   */
  int getGroupDepth();

  /**
   * <code>string created_time = 9;</code>
   */
  String getCreatedTime();
  /**
   * <code>string created_time = 9;</code>
   */
  com.google.protobuf.ByteString
      getCreatedTimeBytes();

  /**
   * <code>string updated_time = 10;</code>
   */
  String getUpdatedTime();
  /**
   * <code>string updated_time = 10;</code>
   */
  com.google.protobuf.ByteString
      getUpdatedTimeBytes();
}
