// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.example.demo.grpc.board;

public final class Board {
  private Board() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_board_BoardDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_board_BoardDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_board_BoardId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_board_BoardId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_board_BoardStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_board_BoardStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_board_BoardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_board_BoardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_board_BoardResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_board_BoardResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013board.proto\022\033com.example.demo.grpc.boa" +
      "rd\"\276\001\n\010BoardDto\022\n\n\002id\030\001 \001(\003\022\017\n\007user_id\030\002" +
      " \001(\003\022\r\n\005title\030\003 \001(\t\022\021\n\timage_url\030\004 \001(\t\022\r" +
      "\n\005likes\030\005 \001(\005\022\020\n\010group_id\030\006 \001(\005\022\021\n\tgroup" +
      "_seq\030\007 \001(\005\022\023\n\013group_depth\030\010 \001(\005\022\024\n\014creat" +
      "ed_time\030\t \001(\t\022\024\n\014updated_time\030\n \001(\t\"\025\n\007B" +
      "oardId\022\n\n\002id\030\001 \001(\003\".\n\013BoardStatus\022\022\n\nSta" +
      "tusCode\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\"B\n\014BoardReque" +
      "st\0222\n\003req\030\001 \001(\0132%.com.example.demo.grpc." +
      "board.BoardDto\"C\n\rBoardResponse\0222\n\003res\030\001" +
      " \001(\0132%.com.example.demo.grpc.board.Board" +
      "Dto2\236\003\n\014BoardService\022f\n\013boardInsert\022).co" +
      "m.example.demo.grpc.board.BoardRequest\032*" +
      ".com.example.demo.grpc.board.BoardRespon" +
      "se\"\000\022f\n\013boardUpdate\022).com.example.demo.g" +
      "rpc.board.BoardRequest\032*.com.example.dem" +
      "o.grpc.board.BoardResponse\"\000\022]\n\tboardRea" +
      "d\022$.com.example.demo.grpc.board.BoardId\032" +
      "(.com.example.demo.grpc.board.BoardStatu" +
      "s\"\000\022_\n\013boardDelete\022$.com.example.demo.gr" +
      "pc.board.BoardId\032(.com.example.demo.grpc" +
      ".board.BoardStatus\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_demo_grpc_board_BoardDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_grpc_board_BoardDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_board_BoardDto_descriptor,
        new String[] { "Id", "UserId", "Title", "ImageUrl", "Likes", "GroupId", "GroupSeq", "GroupDepth", "CreatedTime", "UpdatedTime", });
    internal_static_com_example_demo_grpc_board_BoardId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_demo_grpc_board_BoardId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_board_BoardId_descriptor,
        new String[] { "Id", });
    internal_static_com_example_demo_grpc_board_BoardStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_demo_grpc_board_BoardStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_board_BoardStatus_descriptor,
        new String[] { "StatusCode", "Msg", });
    internal_static_com_example_demo_grpc_board_BoardRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_demo_grpc_board_BoardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_board_BoardRequest_descriptor,
        new String[] { "Req", });
    internal_static_com_example_demo_grpc_board_BoardResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_demo_grpc_board_BoardResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_board_BoardResponse_descriptor,
        new String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
