// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.example.demo.grpc.board;

/**
 * Protobuf type {@code com.example.demo.grpc.board.BoardDto}
 */
public  final class BoardDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.demo.grpc.board.BoardDto)
    BoardDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BoardDto.newBuilder() to construct.
  private BoardDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoardDto() {
    id_ = 0L;
    userId_ = 0L;
    title_ = "";
    imageUrl_ = "";
    likes_ = 0;
    groupId_ = 0;
    groupSeq_ = 0;
    groupDepth_ = 0;
    createdTime_ = "";
    updatedTime_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BoardDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {

            userId_ = input.readInt64();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            imageUrl_ = s;
            break;
          }
          case 40: {

            likes_ = input.readInt32();
            break;
          }
          case 48: {

            groupId_ = input.readInt32();
            break;
          }
          case 56: {

            groupSeq_ = input.readInt32();
            break;
          }
          case 64: {

            groupDepth_ = input.readInt32();
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            createdTime_ = s;
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();

            updatedTime_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Board.internal_static_com_example_demo_grpc_board_BoardDto_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Board.internal_static_com_example_demo_grpc_board_BoardDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BoardDto.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private long userId_;
  /**
   * <code>int64 user_id = 2;</code>
   */
  public long getUserId() {
    return userId_;
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private volatile Object title_;
  /**
   * <code>string title = 3;</code>
   */
  public String getTitle() {
    Object ref = title_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    Object ref = title_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_URL_FIELD_NUMBER = 4;
  private volatile Object imageUrl_;
  /**
   * <code>string image_url = 4;</code>
   */
  public String getImageUrl() {
    Object ref = imageUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      imageUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string image_url = 4;</code>
   */
  public com.google.protobuf.ByteString
      getImageUrlBytes() {
    Object ref = imageUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      imageUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIKES_FIELD_NUMBER = 5;
  private int likes_;
  /**
   * <code>int32 likes = 5;</code>
   */
  public int getLikes() {
    return likes_;
  }

  public static final int GROUP_ID_FIELD_NUMBER = 6;
  private int groupId_;
  /**
   * <code>int32 group_id = 6;</code>
   */
  public int getGroupId() {
    return groupId_;
  }

  public static final int GROUP_SEQ_FIELD_NUMBER = 7;
  private int groupSeq_;
  /**
   * <code>int32 group_seq = 7;</code>
   */
  public int getGroupSeq() {
    return groupSeq_;
  }

  public static final int GROUP_DEPTH_FIELD_NUMBER = 8;
  private int groupDepth_;
  /**
   * <code>int32 group_depth = 8;</code>
   */
  public int getGroupDepth() {
    return groupDepth_;
  }

  public static final int CREATED_TIME_FIELD_NUMBER = 9;
  private volatile Object createdTime_;
  /**
   * <code>string created_time = 9;</code>
   */
  public String getCreatedTime() {
    Object ref = createdTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      createdTime_ = s;
      return s;
    }
  }
  /**
   * <code>string created_time = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedTimeBytes() {
    Object ref = createdTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      createdTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATED_TIME_FIELD_NUMBER = 10;
  private volatile Object updatedTime_;
  /**
   * <code>string updated_time = 10;</code>
   */
  public String getUpdatedTime() {
    Object ref = updatedTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      updatedTime_ = s;
      return s;
    }
  }
  /**
   * <code>string updated_time = 10;</code>
   */
  public com.google.protobuf.ByteString
      getUpdatedTimeBytes() {
    Object ref = updatedTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      updatedTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (userId_ != 0L) {
      output.writeInt64(2, userId_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (!getImageUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imageUrl_);
    }
    if (likes_ != 0) {
      output.writeInt32(5, likes_);
    }
    if (groupId_ != 0) {
      output.writeInt32(6, groupId_);
    }
    if (groupSeq_ != 0) {
      output.writeInt32(7, groupSeq_);
    }
    if (groupDepth_ != 0) {
      output.writeInt32(8, groupDepth_);
    }
    if (!getCreatedTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, createdTime_);
    }
    if (!getUpdatedTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, updatedTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userId_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (!getImageUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imageUrl_);
    }
    if (likes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, likes_);
    }
    if (groupId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, groupId_);
    }
    if (groupSeq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, groupSeq_);
    }
    if (groupDepth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, groupDepth_);
    }
    if (!getCreatedTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, createdTime_);
    }
    if (!getUpdatedTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, updatedTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BoardDto)) {
      return super.equals(obj);
    }
    BoardDto other = (BoardDto) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getUserId()
        == other.getUserId());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getImageUrl()
        .equals(other.getImageUrl());
    result = result && (getLikes()
        == other.getLikes());
    result = result && (getGroupId()
        == other.getGroupId());
    result = result && (getGroupSeq()
        == other.getGroupSeq());
    result = result && (getGroupDepth()
        == other.getGroupDepth());
    result = result && getCreatedTime()
        .equals(other.getCreatedTime());
    result = result && getUpdatedTime()
        .equals(other.getUpdatedTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + IMAGE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getImageUrl().hashCode();
    hash = (37 * hash) + LIKES_FIELD_NUMBER;
    hash = (53 * hash) + getLikes();
    hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGroupId();
    hash = (37 * hash) + GROUP_SEQ_FIELD_NUMBER;
    hash = (53 * hash) + getGroupSeq();
    hash = (37 * hash) + GROUP_DEPTH_FIELD_NUMBER;
    hash = (53 * hash) + getGroupDepth();
    hash = (37 * hash) + CREATED_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedTime().hashCode();
    hash = (37 * hash) + UPDATED_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatedTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BoardDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoardDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoardDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoardDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoardDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoardDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoardDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BoardDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BoardDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BoardDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BoardDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BoardDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BoardDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.grpc.board.BoardDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.grpc.board.BoardDto)
      com.example.demo.grpc.board.BoardDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Board.internal_static_com_example_demo_grpc_board_BoardDto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Board.internal_static_com_example_demo_grpc_board_BoardDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BoardDto.class, Builder.class);
    }

    // Construct using com.example.demo.grpc.board.BoardDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      userId_ = 0L;

      title_ = "";

      imageUrl_ = "";

      likes_ = 0;

      groupId_ = 0;

      groupSeq_ = 0;

      groupDepth_ = 0;

      createdTime_ = "";

      updatedTime_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Board.internal_static_com_example_demo_grpc_board_BoardDto_descriptor;
    }

    public BoardDto getDefaultInstanceForType() {
      return BoardDto.getDefaultInstance();
    }

    public BoardDto build() {
      BoardDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public BoardDto buildPartial() {
      BoardDto result = new BoardDto(this);
      result.id_ = id_;
      result.userId_ = userId_;
      result.title_ = title_;
      result.imageUrl_ = imageUrl_;
      result.likes_ = likes_;
      result.groupId_ = groupId_;
      result.groupSeq_ = groupSeq_;
      result.groupDepth_ = groupDepth_;
      result.createdTime_ = createdTime_;
      result.updatedTime_ = updatedTime_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BoardDto) {
        return mergeFrom((BoardDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BoardDto other) {
      if (other == BoardDto.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getImageUrl().isEmpty()) {
        imageUrl_ = other.imageUrl_;
        onChanged();
      }
      if (other.getLikes() != 0) {
        setLikes(other.getLikes());
      }
      if (other.getGroupId() != 0) {
        setGroupId(other.getGroupId());
      }
      if (other.getGroupSeq() != 0) {
        setGroupSeq(other.getGroupSeq());
      }
      if (other.getGroupDepth() != 0) {
        setGroupDepth(other.getGroupDepth());
      }
      if (!other.getCreatedTime().isEmpty()) {
        createdTime_ = other.createdTime_;
        onChanged();
      }
      if (!other.getUpdatedTime().isEmpty()) {
        updatedTime_ = other.updatedTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      BoardDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (BoardDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 user_id = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 user_id = 2;</code>
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 user_id = 2;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private Object title_ = "";
    /**
     * <code>string title = 3;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder setTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private Object imageUrl_ = "";
    /**
     * <code>string image_url = 4;</code>
     */
    public String getImageUrl() {
      Object ref = imageUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string image_url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      Object ref = imageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string image_url = 4;</code>
     */
    public Builder setImageUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string image_url = 4;</code>
     */
    public Builder clearImageUrl() {
      
      imageUrl_ = getDefaultInstance().getImageUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string image_url = 4;</code>
     */
    public Builder setImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageUrl_ = value;
      onChanged();
      return this;
    }

    private int likes_ ;
    /**
     * <code>int32 likes = 5;</code>
     */
    public int getLikes() {
      return likes_;
    }
    /**
     * <code>int32 likes = 5;</code>
     */
    public Builder setLikes(int value) {
      
      likes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 likes = 5;</code>
     */
    public Builder clearLikes() {
      
      likes_ = 0;
      onChanged();
      return this;
    }

    private int groupId_ ;
    /**
     * <code>int32 group_id = 6;</code>
     */
    public int getGroupId() {
      return groupId_;
    }
    /**
     * <code>int32 group_id = 6;</code>
     */
    public Builder setGroupId(int value) {
      
      groupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 group_id = 6;</code>
     */
    public Builder clearGroupId() {
      
      groupId_ = 0;
      onChanged();
      return this;
    }

    private int groupSeq_ ;
    /**
     * <code>int32 group_seq = 7;</code>
     */
    public int getGroupSeq() {
      return groupSeq_;
    }
    /**
     * <code>int32 group_seq = 7;</code>
     */
    public Builder setGroupSeq(int value) {
      
      groupSeq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 group_seq = 7;</code>
     */
    public Builder clearGroupSeq() {
      
      groupSeq_ = 0;
      onChanged();
      return this;
    }

    private int groupDepth_ ;
    /**
     * <code>int32 group_depth = 8;</code>
     */
    public int getGroupDepth() {
      return groupDepth_;
    }
    /**
     * <code>int32 group_depth = 8;</code>
     */
    public Builder setGroupDepth(int value) {
      
      groupDepth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 group_depth = 8;</code>
     */
    public Builder clearGroupDepth() {
      
      groupDepth_ = 0;
      onChanged();
      return this;
    }

    private Object createdTime_ = "";
    /**
     * <code>string created_time = 9;</code>
     */
    public String getCreatedTime() {
      Object ref = createdTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createdTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string created_time = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedTimeBytes() {
      Object ref = createdTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createdTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_time = 9;</code>
     */
    public Builder setCreatedTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string created_time = 9;</code>
     */
    public Builder clearCreatedTime() {
      
      createdTime_ = getDefaultInstance().getCreatedTime();
      onChanged();
      return this;
    }
    /**
     * <code>string created_time = 9;</code>
     */
    public Builder setCreatedTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdTime_ = value;
      onChanged();
      return this;
    }

    private Object updatedTime_ = "";
    /**
     * <code>string updated_time = 10;</code>
     */
    public String getUpdatedTime() {
      Object ref = updatedTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updatedTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string updated_time = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUpdatedTimeBytes() {
      Object ref = updatedTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updatedTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string updated_time = 10;</code>
     */
    public Builder setUpdatedTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updatedTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string updated_time = 10;</code>
     */
    public Builder clearUpdatedTime() {
      
      updatedTime_ = getDefaultInstance().getUpdatedTime();
      onChanged();
      return this;
    }
    /**
     * <code>string updated_time = 10;</code>
     */
    public Builder setUpdatedTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updatedTime_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.demo.grpc.board.BoardDto)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.grpc.board.BoardDto)
  private static final BoardDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BoardDto();
  }

  public static BoardDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoardDto>
      PARSER = new com.google.protobuf.AbstractParser<BoardDto>() {
    public BoardDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BoardDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BoardDto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BoardDto> getParserForType() {
    return PARSER;
  }

  public BoardDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

