// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.example.demo.grpc.board;

public interface BoardStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.board.BoardStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 StatusCode = 1;</code>
   */
  int getStatusCode();

  /**
   * <code>string msg = 2;</code>
   */
  String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
