// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.example.demo.grpc.board;

public interface BoardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.board.BoardResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.grpc.board.BoardDto res = 1;</code>
   */
  boolean hasRes();
  /**
   * <code>.com.example.demo.grpc.board.BoardDto res = 1;</code>
   */
  BoardDto getRes();
  /**
   * <code>.com.example.demo.grpc.board.BoardDto res = 1;</code>
   */
  BoardDtoOrBuilder getResOrBuilder();
}
