// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.example.demo.grpc.board;

public interface BoardIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.board.BoardId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
