// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.example.demo.grpc.board;

public interface BoardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.board.BoardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.grpc.board.BoardDto req = 1;</code>
   */
  boolean hasReq();
  /**
   * <code>.com.example.demo.grpc.board.BoardDto req = 1;</code>
   */
  BoardDto getReq();
  /**
   * <code>.com.example.demo.grpc.board.BoardDto req = 1;</code>
   */
  BoardDtoOrBuilder getReqOrBuilder();
}
